# cluttered_environment.yaml
environment:
  name: "Cluttered Environment"
  description: "Environment with obstacles requiring navigation planning"
  dimensions: [4.0, 4.0, 2.0]
  scale_factor: 1.0
  
  workspaces:
    - name: "Robot 1 Workspace"
      position: [0.8, 1.2, 0.0]
      dimensions: [1.5, 1.5, 2.0]
    
    - name: "Robot 2 Workspace"
      position: [3.2, 2.8, 0.0]
      dimensions: [1.5, 1.5, 2.0]
    
    - name: "Shared Workspace"
      position: [2.0, 2.0, 0.0]
      dimensions: [0.8, 0.8, 2.0]
  
  stations:
    - name: "Component Supply"
      position: [0.5, 0.5, 0.5]
      type: "supply"
    
    - name: "Assembly Area"
      position: [2.0, 2.0, 0.5]
      type: "assembly"
    
    - name: "Inspection Station"
      position: [3.5, 3.5, 0.5]
      type: "inspection"
  
  objects: []
  
  obstacles:
    - name: "Obstacle 1"
      type: "box"
      position: [1.5, 1.0, 0.5]
      dimensions: [0.5, 0.2, 1.0]
    
    - name: "Obstacle 2"
      type: "box"
      position: [2.0, 1.5, 0.5]
      dimensions: [0.2, 0.5, 1.0]
    
    - name: "Obstacle 3"
      type: "cylinder"
      position: [2.5, 2.5, 0.5]
      dimensions: [0.3, 1.0, 0.0]  # radius, height
    
    - name: "Obstacle 4"
      type: "box"
      position: [1.0, 2.7, 0.5]
      dimensions: [0.3, 0.3, 0.8]
    
    - name: "Obstacle 5"
      type: "box"
      position: [3.0, 1.2, 0.5]
      dimensions: [0.4, 0.4, 0.6]